



## 获取项目当中的接口
GET http://localhost:9201/admin-api/debug/endpoints



### asdasd



GET https://api.tikhub.io/api/v1/douyin/web/fetch_user_post_videos?sec_user_id=MS4wLjABAAAAMd8Nmzv60Y7XkRdq1y67J8T1NQiLIDQfcpFwPxB4tN7H9OLVMxmze50fndhxIjQR&max_cursor=0&count=50&filter_type=0&cookie
Authorization: Bearer oJMgD/I5zGmlg0+tKo+48j7VBH6Nf5VvxTT1lGysaMaw0FaGeWWjVWOhEQ==